name: Biome
'on':
  workflow_call: null
permissions:
  contents: read
jobs:
  biome:
    name: Lint & format (biome ci)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup workspace
        uses: ./.github/actions/setup
      - name: Lint & format (biome ci)
        run: pnpm run check:ci
    timeout-minutes: 15
