name: Build
'on':
  workflow_call: null
permissions:
  contents: read
jobs:
  build:
    name: ubuntu / node 24
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup workspace
        uses: ./.github/actions/setup
      - name: Build widget bundle
        run: pnpm build
    timeout-minutes: 15
