name: Typecheck
'on':
  workflow_call: null
permissions:
  contents: read
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup workspace
        uses: ./.github/actions/setup
      - name: Type check
        run: pnpm typecheck
    timeout-minutes: 15
